jobs:

#---------------------------------------------------------------#
#---------------------------- SecOps ---------------------------#
#---------------------------------------------------------------#

# # Set up Network - AWS IAM roles, profiles, VPCs etc. with TERRAFORM
#   - name: setup_net
#     type: runSh
#     steps:
#       - IN: net_tf_state
#       - IN: net_conf
#       - IN: aws_creds
#         switch: off
#       - IN: secops_repo
#         switch: off
#       - TASK:
#         - script: . /build/IN/secops_repo/gitRepo/infra/shipUtil.sh
#         - script: . /build/IN/secops_repo/gitRepo/infra/awsSetupIAM/provNetwork.sh create
#       - OUT: ami_vpc_conf
#       - OUT: test_vpc_conf
#       - OUT: prod_vpc_conf
#       - OUT: net_tf_state
#     on_success:
#       - script: echo "SUCCESS"
#     on_failure:
#       - script: echo "FAILURE"
#     always:
#       - script: . /build/IN/secops_repo/gitRepo/infra/shipUtil.sh && . /build/IN/secops_repo/gitRepo/infra/archiveState.sh infra/awsSetupIAM net_tf_state
#     flags:
#       - amiBuildCI

# Build Machine image - AWS AMI used to deploy ECS VMs with PACKER
# using Shippable CI job for performing AMI build
  - name: demo-secops-ci_runCI
    type: runCI
    steps:
      - IN: aws_creds
        switch: off
      - IN: secops_repo
        switch: off
      # - IN: ami_vpc_conf
      - OUT: ami_sec_approved
    on_success:
      - script: echo "SUCCESS"
    on_failure:
      - script: echo "FAILURE"
    flags:
      - amiBuildCI

# # Deprovision Network
#   - name: de_prov_net
#     type: runSh
#     steps:
#       - IN: setup_net
#         switch: off
#       - IN: net_tf_state
#       - IN: net_conf
#         switch: off
#       - IN: aws_creds
#         switch: off
#       - IN: secops_repo
#         switch: off
#       - TASK:
#         - script: . /build/IN/secops_repo/gitRepo/infra/shipUtil.sh
#         - script: . /build/IN/secops_repo/gitRepo/infra/awsSetupIAM/provNetwork.sh destroy
#       - OUT: net_tf_state
#     on_success:
#       - script: echo "SUCCESS"
#     on_failure:
#       - script: echo "FAILURE"
#     always:
#       - script: . /build/IN/secops_repo/gitRepo/infra/shipUtil.sh && . /build/IN/secops_repo/gitRepo/infra/archiveState.sh infra/awsSetupIAM net_tf_state
#     flags:
#       - amiBuildCI
